// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfqtamzyqbfhdowcfwei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmcXRhbXp5cWJmaGRvd2Nmd2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MTExMDAsImV4cCI6MjA4NDQ4NzEwMH0.hF_ZR1SScunOM4Z63waBas2XwoZ3jwPLZXFhqtPJTsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});